export const CHANGE_TO_DIRECTED_MESSAGE_MODE = 'CHANGE_TO_DIRECTED_MESSAGE_MODE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const GET_DATA_USER = 'GET_USER_DATA';
